version: '3'

services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"

  #  recognizer:
  #    build:
  #      context: ./recognizer
  #    restart: always
  #    ports:
  #      - "5001:5001"

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"