version: '3'

services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          memory: 1800M
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"